services:

  jenkins:
    image: jenkins:latest
    build:
      context: ./config
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./logs/jenkins_home:/var/jenkins_home
      - .:/var/jenkins_home/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - 8200:8200
    # volumes:
    #   - ./logs/vault_logs:
    environment:
      - VAULT_ADDR='http://0.0.0.0:8200'
      - VAULT_DEV_ROOT_TOKEN_ID='myroot'
    networks:
      - net

networks:
  net:
    name: net
    driver: bridge