pipeline {
  agent any

  parameters {
    // Option 1
    // activeChoice(
    //   name: 'States',
    //   description: 'Select a state option',
    //   choiceType: 'PT_SINGLE_SELECT',
    //   script: [
    //     $class: 'GroovyScript',
    //     script: [
    //       classpath: [],
    //       sandbox: true,
    //       script:
    //         'return ["A_State", "B_State"]'
    //     ],
    //     fallbackScript: [
    //       classpath: [],
    //       sandbox: true,
    //       script:
    //         'return ["Error for States"]'
    //     ]
    //   ]
    // )
    
    // Option 2
    choice (
      name: 'States',
      choices: ["A_State", "B_State"],
      description: 'Select a state option'
    )

    activeChoiceHtml(
      name: 'Cities',
      description: 'Select a city option',
      choiceType: 'ET_FORMATTED_HTML',
      referencedParameters: 'States', 
      script: [
        $class: 'GroovyScript',
        script: [
          classpath: [],
          sandbox: false,
          script:
            '''
              if (States.equals("A_State")) {
                return "<input name="value" value="A_State" class="setting-input" type="text">" 
              }
              else if (States.equals("B_State")) {
                return "<input name="value" value="A_State" class="setting-input" type="text">" 
              }
            '''
        ],
        fallbackScript: [
          classpath: [],
          sandbox: false,
          script:
            'return ["Error for Cities"]'
        ]
      ]
    )

    // reactiveChoice(
    //   name: 'Cities',
    //   description: 'Select a city option',
    //   choiceType: 'PT_SINGLE_SELECT',
    //   referencedParameters: 'States', 
    //   script: [
    //     $class: 'GroovyScript',
    //     script: [
    //       classpath: [],
    //       sandbox: true,
    //       script:
    //         '''
    //           if (States.equals("A_State")) {
    //             return ["A_Cities1","A_Cities2","A_Cities3","A_Cities4","A_Cities5","A_Cities6"]
    //           }
    //           else if (States.equals("B_State")) {
    //             return ["B_Cities1","B_Cities2","B_Cities3","B_Cities4"]
    //           }
    //         '''
    //     ],
    //     fallbackScript: [
    //       classpath: [],
    //       sandbox: true,
    //       script:
    //         'return ["Error for Cities"]'
    //     ]
    //   ]
    // )
  }

  stages {
    stage('Build') {
      steps {
        echo "Showing ${params.States}"
        echo "Showing ${params.Cities}"
      }
    }
  }
}