pipeline {
  agent any

  parameters {
    // choice (
    //   name: 'ACTION'.
    //   choices: ['get', 'put'],
    //   description: 'Use get for existing secret and push for creating a new one!'
    // )

    activeChoice(
      name: 'States',
      description: 'Select a state option',
      choiceType: 'PT_MULTI_SELECT',
      script: [
        $class: 'GroovyScript',
        script: [
          classpath: [],
          sandbox: true,
          script:
            'return ["A State", "B State", "C State"]'
        ],
        fallbackScript: [
          classpath: [],
          sandbox: true,
          script:
            'return ["Error"]'
        ]
      ]
    )
  }

  stages {
    stage('Build') {
      steps {
        echo "Showing ${params.States}"
      }
    }
  }
}