version: '3.7'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
    restart: unless-stopped
    networks:
      - vault-net
    command: server -dev -dev-root-token-id=root

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vault_db
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - vault-net

networks:
  vault-net:
    driver: bridge

volumes:
  vault_data:
