services:

  jenkins:
    image: jenkins:2.460-jdk17
    build:
      context: ../../containerization/docker
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./logs/jenkins_home:/var/jenkins_home
      - .:/var/jenkins_home/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

networks:
  net:
    name: net
    driver: bridge